[package]
name = "osrank-experiments"
version = "0.1.0"
authors = ["Alfredo Di Napoli <alfredo.dinapoli@gmail.com>"]
edition = "2018"

[package.metadata]
assets = "data"

[lib]

name = "osrank"
path = "src/lib.rs"

[[bin]]
name = "osrank-test"
path = "bin/main.rs"

[[bin]]
name = "osrank-source-dependencies"
path = "bin/source_dependencies.rs"
required-features = ["build-binary"]

[features]

build-binary = ["csv"]

[dependencies]

petgraph = "0.4.13"
fraction = "0.6"
serde = { version = "1.0.60", features = ["derive"]}
serde_json = "1.0.40"

# Binary-only dependencies
# See: https://stackoverflow.com/questions/35711044/how-can-i-specify-binary-only-dependencies
csv = { version = "1.1", optional = true }
