steps:
  - label: 'Code Coverage (experimental)'
    command: |
        cargo kcov -j2 -v --all -o kcov_coverage_report;
        kcov --merge --exclude-pattern=/cache/cargo --verify kcov_coverage_report;
        bash <(curl -s https://codecov.io/bash) -s kcov_coverage_report
    env:
      DOCKER_IMAGE: "gcr.io/opensourcecoin/osrank-build@sha256:55ee1268f2ccddbcd708842476fcaa60abb18d9abf966bdfae641669649e7fea"
    agents:
      docker: "true"
